### ISSUE TITLE
Not reloading when changing template files (.html) but reloading when changing PY files (DEBUG)

### ISSUE THREAD

**Issue by martinlombana** [adamchainz/django-browser-reload#107]
### Python Version

3.10

### Django Version

4.1

### Package Version

1.6.0

### Browser

EDGE 103.0.1264.77 (Official build) (64-bit)

### Description

When I change .py files, the reload works as expected. But when I change html template files, inside the template folder of an app, or any other place, the reload is not triggered. Neither is the runserver reload, so it might have to do something with Django. But if there is a fix to make it work, every time we change HTML templates, it would be great. I am using jinja2 templates, and I made sure that the reload code is injected (but not that that could be the issue, because the reload is triggered, as I said, when .py files are changed). I tried several things inside DJANGO, but none of them worked. 

Thanks a lot,

**Comment by adamchainz** [comment]
Can you show me your `TEMPLATES` setting?

The Jinja2 code currently only looks for `FileSystemLoader`:

https://github.com/adamchainz/django-browser-reload/blob/c610c67860feee02f9f035829c975704fb85ee7a/src/django_browser_reload/views.py#L49-L63

Perhaps you are using a different loader.

**Comment by adamchainz** [comment]
Closing due to no reply

**Comment by wgordon17** [comment]
And for those that still like using `runserver_plus`, this PR from django_extensions gets things working for Template changes 👍 https://github.com/django-extensions/django-extensions/pull/1796
