### ISSUE TITLE
Browser not reloading 

### ISSUE THREAD

**Issue by datencoach** [adamchainz/django-browser-reload#124]
### Python Version

3.10.6

### Django Version

4.1.2

### Package Version

1.6.0

### Browser

Chrome, Firefox, Safari

### Description

Dear Adam, it is me again (https://github.com/adamchainz/django-browser-reload/issues/68). Sorry to open this issue again, but I wanted to let you know that me problem is back.

When I startet a new project everything worked fine. Until now. I did not work on this project for a few weeks and when I now updated wagtail, django and django-tailwind I noticed that the reload stopped working again. 

I spend serval hours debugging yesterday, but was not able to find the problem. But I figured out that the route "/__reload__/events/" seems to be the problem. Not exactly the route as the url and view are working and send a 200 http-code, but no pings are sent.

Broken project (same picture on url 127.0.0.1:8000):
![image](https://user-images.githubusercontent.com/51292314/198517296-ba6ce6fa-d27f-40e6-b7cd-a914529bd927.png)

Working project:
![image](https://user-images.githubusercontent.com/51292314/198517899-5227b6a0-937d-405d-a9a5-7b55abd6f121.png)

Do you have any ideas what could prevent that the ping events are send? I can see them on views.py, but they do not arrive at the browser. 

I totally understand if you close this straight away as we already spent time on this not finding an answer.

Thanks and beste Regards, Thomas

**Comment by adamchainz** [comment]
> when I now updated wagtail, django and django-tailwind I noticed that the reload stopped working again.

Did you try going back to the old versions? This would narrow it down to one of the packages. Then you could maybe find out which is responsible.

**Comment by datencoach** [comment]
Yes, I tried a fresh virtual environment with the old package versions, but same result. Seems to be coincidence.

**Comment by adamchainz** [comment]
Okay, well I'm afraid if there’s no info to go on, then I can’t really help... 😅

Did you try the example project in this repo? If that works for you then maybe something in your project is causing the problem, and you can try cutting things out until you find the cause.
