### ISSUE TITLE
reload event ever received when django is behind the reverse proxy

### ISSUE THREAD

**Issue by E5presso** [adamchainz/django-browser-reload#130]
### Python Version

3.10

### Django Version

4.1.2

### Package Version

1.6.0

### Browser

Chrome

### Description

I use django as front service and api service container in docker same time.
I have to manage sub path based routing so I decided to use nginx as reverse proxy.

but when I run django with reverse proxy. The browser never received reload event from server. (and browser just reloaded when the worker long polling was timed out.)

here's my nginx.conf

```
worker_processes 4;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location /api/web {
            return 302 /api/web/;
        }
        location /api/web/ {
            proxy_pass http://web:8000/;
        }

        location / {
            proxy_pass http://front:80/;
        }
    }
}
```

Hope that I can get the solution. thank you! :)

**Comment by E5presso** [comment]
I got the solution and It's pretty simple.

because django-browser-reload uses javascript EventSource, It has to configure some settings in nginx for reverse proxying.
here's the settings that you'd need.

proxy_set_header Connection '';
proxy_http_version 1.1;
chunked_transfer_encoding off;
proxy_buffering off;
proxy_cache off;

So my final config file should be like this.

worker_processes 4;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location /api/web {
            return 302 /api/web/;
        }
        location /api/web/ {
            proxy_pass http://web:8000/;
        }

        location / {
            proxy_pass http://front:80/;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
        }
    }
}

I hope this answer helps someone like me struggling with kinda situations :)

**Comment by adamchainz** [comment]
Thanks for sharing your solution and closing.
