### ISSUE TITLE
Installation Docs

### ISSUE THREAD

**Issue by wsvincent** [adamchainz/django-browser-reload#182]
### Description

You could be more specific about "where" to place it in the MIDDLEWARE. A newcomer won't know about the [default ordering](https://docs.djangoproject.com/en/4.2/ref/middleware/#middleware-ordering), and the default Django project doesn't explicitly list `GZipMiddleware.`

Awesome project!

**Comment by adamchainz** [comment]
Can you suggest a wording change? The only constraint is "somewhere after `GZipMiddleware` and similar middleware".

**Comment by adamchainz** [comment]
Closing as I think the current wording is enough, but happy to see a PR.
