### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by nilslindemann** [adamchainz/django-browser-reload#200]
### Python Version

3.10.12

### Django Version

4.2.2

### Package Version

1.11.0

### Browser

Latest Firefox, Latest Chromium

### Description

I did as described [here](https://pypi.org/project/django-browser-reload/), no luck. No JavaScript is injected into the page, no auto reloading of the browser tab happens, no trace back is shown. I also installed pywatchman, as recommened [here](https://github.com/adamchainz/django-browser-reload/blob/main/example/requirements.txt), no results.

I also tried with this example repo. I followed [these instructions](https://github.com/adamchainz/django-browser-reload/tree/main/example). (I had to manually install the [daphne](https://docs.djangoproject.com/en/4.2/howto/deployment/asgi/daphne/) package) Then ...

* `DEBUG=1 python manage.py runserver` logs to the linux console:

  ```
  Application instance <Task pending name='Task-6' coro=<ASGIStaticFilesHandler.__call__() running at 
  /home/nils/Django/django-browser-reload-main/example/.venv/lib/python3.10/site- 
  packages/django/contrib/staticfiles/handlers.py:101> wait_for=<Future pending cb=[Task.task_wakeup()]>> for connection 
  <WebRequest at 0x7f12954b8670 method=GET uri=/__reload__/events/ clientproto=HTTP/1.1> took too long to shut down 
  and was killed.
  ```

* ... `DEBUG=1 python manage.py runserver --noasgi` logs to the Javascript console in Chrome ...

  ```
  Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
  Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
  Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
  127.0.0.1/:15     GET http://127.0.0.1:8000/static/django-browser-reload/reload-listener.js net::ERR_ABORTED 404 (Not 
  Found)
  127.0.0.1/:8     GET http://127.0.0.1:8000/static/main.css net::ERR_ABORTED 404 (Not Found)
  ```
  
  ... and in Firefox:
  
  ```
  Loading failed for the <script> with source “http://127.0.0.1:8000/static/django-browser-reload/reload-listener.js”. 
  127.0.0.1:8000:15:183
  ```

**Comment by adamchainz** [comment]
Please try running the project on a different port. It looks like you may have declared a permissions policy or similar to the browser for the origin `http://127.0.0.1:8000/`, and that is persisting and preventing Django-browser-reload from working.

**Comment by nilslindemann** [comment]
I tried `DEBUG=1 python manage.py runserver 8080 --noasgi` but it does not work. It seemingly can not load the CSS, which is weird, because it did when I created this venv the first time.

`pip list` inside the venv gives ...

```
Package               Version Editable project location
--------------------- ------- --------------------------------------------
asgiref               3.7.2
attrs                 23.1.0
autobahn              23.6.2
Automat               22.10.0
cffi                  1.15.1
constantly            15.1.0
cryptography          41.0.3
daphne                4.0.0
Django                4.2.1
django-browser-reload 1.11.0  /home/nils/Django/django-browser-reload-main
hyperlink             21.0.0
idna                  3.4
incremental           22.10.0
Jinja2                3.1.2
MarkupSafe            2.1.3
pip                   23.2.1
pyasn1                0.5.0
pyasn1-modules        0.3.0
pycparser             2.21
pyOpenSSL             23.2.0
pywatchman            1.4.1
service-identity      23.1.0
setuptools            59.6.0
six                   1.16.0
sqlparse              0.4.4
Twisted               23.8.0
txaio                 23.1.1
typing_extensions     4.7.1
wheel                 0.41.2
zope.interface        6.0
```

**Comment by nilslindemann** [comment]
Meanwhile, I can see the script before the body closing tag in the DOM, but when I open that link in a new tab, as well as the stylesheet, I get a Django message "page not found".

**Comment by adamchainz** [comment]
I looked further. Static assets were broken in WSGI mode, I think some complexity with daphne's staticfiles integration. PR #201 has fixed the issue by avoiding installing Daphne in WSGI mode, using another environment variable, plus it added Daphne to requirements.

Can you try again, following the new instructions? Thanks for your report.

**Comment by nilslindemann** [comment]
Thank you very much, @adamchainz, for taking the time to look into that. This is a big improvement. My test results in Chrome and Firefox are as follows:

* It fully works now in WSGI mode (`DEBUG=1 python manage.py runserver`), using Django templates. It will detect changes to the CSS, the template files, and the Python files. (server restart)

* The Ninja version detects changes to CSS and template files, but changes to the views.py are not detected, not even if I reload without cache or when I manually restart the server. No idea what happens here.

* In ASGI mode, it still does not reload anything, and logs messages like the following:

  ```
  Application instance <Task pending name='Task-2' coro=<ASGIStaticFilesHandler.__call__() running at /home/nils/Django/django-browser-reload-main/example/.venv/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py:101> wait_for=<Future pending cb=[Task.task_wakeup()]>> for connection <WebRequest at 0x7f41f7315420 method=GET uri=/__reload__/events/ clientproto=HTTP/1.1> took too long to shut down and was killed.
  ```

**Comment by nilslindemann** [comment]
Regarding the <strike>Ninja</strike> <ins>Jinja</ins> templates, this actually works. I made an error and only changed the `index_django` function. It works when I edit the `index_jinja` function. Sorry, my mistake.

Regarding the ASGI mode, I checked again. This now works, it did not yesterday. Probably I had an outdated version of the repo.

Still, I sometimes have to save twice, otherwise it will not reload. I have uploaded an example for [Firefox](https://www.youtube.com/watch?v=87tn9kciJK0) and one for [Chromium](https://www.youtube.com/watch?v=vzO_s3ZwZ0A) to YouTube. You can see in the status bar of the editor (top left) when I save the file. Sometimes, saving it once is not enough, for example in the Firefox example, after changing the background to azure the second time. Also tested in other editors.

**Comment by adamchainz** [comment]
Hmm, there might be some timing bug in ASGI mode. I'm afraid I don't use it myself at the moment. If we can find something more specific than “saving twice required“ then we can narrow in on the problem, but otherwise I'm not sure I can easily do something.

**Comment by nilslindemann** [comment]
It is ok. I will use WSGI mode. Thanks for your time. May I change the title?

**Comment by adamchainz** [comment]
Haha thanks
