### ISSUE TITLE
Wagtail and django-browser-reload: Errors After Disabling Language Prefix for Default Language

### ISSUE THREAD

**Issue by nickAalst** [adamchainz/django-browser-reload#205]
### Description

I am using the django-browser-reload in a project that I'm working on, and it works amazingly. But today I noticed a slight problem, and I don't know how to fix it.

It's only a small thing.
This is a Wagtail project, and I have a multilanguage site; therefore, I'm using Internationalization for the translations. I didn't want a prefix for the default language, so I added 'prefix_default_language=False' as described here in the Wagtail docs: https://docs.wagtail.org/en/stable/advanced_topics/i18n.html#bypass-language-prefix-for-the-default-language

From the moment I restarted my server, I got these errors repeatedly:
Not Found: /reload/events/
[08/Sep/2023 13:40:31] "GET /reload/events/ HTTP/1.1" 404 3712
Not Found: /reload/events/
[08/Sep/2023 13:40:32] "GET /reload/events/ HTTP/1.1" 404 3712

Sometimes it was a few seconds apart, and other times it was a few times every second.

**Comment by adamchainz** [comment]
Those requests are from the script running in your browser trying to reconnect to the view. I would guess that your change to the URLs moved or disabled the URL, causing 404s. Reloading the tab would solve this. (Only the last opened tab makes requests, the others stop running.)
