### ISSUE TITLE
The middleware doesn't work properly in asgi mode

### ISSUE THREAD

**Issue by CrazyUmka** [adamchainz/django-browser-reload#215]
### Python Version

3.12.0

### Django Version

4.2.6

### Package Version

1.12.0

### Description

I have already described the behavior in the next issue: https://github.com/adamchainz/django-htmx/issues/381

**Comment by adamchainz** [comment]
Waiting for reply on django-htmx issue.

**Comment by adamchainz** [comment]
This was fixed in #225.
