### ISSUE TITLE
Not Implemented /events 501 error

### ISSUE THREAD

**Issue by Kyvex** [adamchainz/django-browser-reload#227]
### Python Version

3.11.0

### Django Version

4.1.2

### Package Version

1.12.1

### Browser

Google

### Description

When running my server I get this repeating message. Any ideas?
![Screenshot 2023-11-28 at 6 07 41 PM](https://github.com/adamchainz/django-browser-reload/assets/49984401/8e3ee850-b527-48af-a931-a1ff0ff21904)

**Comment by Kyvex** [comment]
What's weird is that no workers are showing in my console. This is all that is shown.
<img width="321" alt="Screenshot 2023-11-29 at 9 26 14 AM" src="https://github.com/adamchainz/django-browser-reload/assets/49984401/9d1b4043-6bfc-4e32-a77f-12503d5b7b3a">

**Comment by GopyDev** [comment]
I'm getting same error.
I'm using Daphne and running app like this

`daphne projectname.asgi:application`

but when running it, showing error like this
![image](https://github.com/adamchainz/django-browser-reload/assets/20521467/8945a96a-9ca7-4ea2-a933-21b47e354dec)

Here is what I can see on browser console as an error.
![image](https://github.com/adamchainz/django-browser-reload/assets/20521467/cfc4e4c5-8456-4fb0-a51c-d2d3d7d1eea0)


Any ideas about this error?

**Comment by adamchainz** [comment]
Ah okay, so you’re using Daphne, so aync. Now I remember that async mode requires Django 4.2+. We decided to make django-browser-reload return “501 Not Implemented” on older Django versions:

https://github.com/adamchainz/django-browser-reload/blob/97754e2382b1a28df56332eabce58781f4c953de/src/django_browser_reload/views.py#L158-L164

So the solution here is to upgrade Django. Perhaps this could be better documented?
