### ISSUE TITLE
Can't find listener.js

### ISSUE THREAD

**Issue by juliu1902** [adamchainz/django-browser-reload#231]
### Python Version

3.11.6

### Django Version

4.2.1

### Package Version

1.12.1 

### Browser

Firefox, Chrome

### Description

I have followed the Readme's installation. The script is inserted correctly, as I can see it in the Inspector. But I always get the following errors when I run `python manage.py runserver`: 

```bash
GET
http://127.0.0.1:8000/static/django-browser-reload/reload-listener.js  [HTTP/1.1 404 Not Found 15ms]

Loading failed for the <script> with source “http://127.0.0.1:8000/static/django-browser-reload/reload-listener.js”.
```

I tried to run the example, it's working fine. The funny thing is that hot reloading on my own project works after running the example. So I guess there is a problem with creating the staticfiles. Maybe I overlooked something?

**Comment by adamchainz** [comment]
This seems like an issue with your static setup. What are you using?

**Comment by juliu1902** [comment]
> What are you using? Do other static files work?

I ran the collectstatic command and django wasn't able to find any staticfiles at all, not even my input.css. What might be relevant is that I am using tailwind as css framework This is what my directory looks like:

```
.
├── README.md
├── db.sqlite3
├── infrastructure_platform
│   ├── __init__.py
│   ├── __pycache__
│   ├── asgi.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── manage.py
├── package-lock.json
├── package.json
├── requirements.txt
└── serverdocumentation
    ├── __init__.py
    ├── __pycache__
    ├── admin.py
    ├── apps.py
    ├── migrations
    ├── models.py
    ├── static
    ├── tailwind.config.js
    ├── templates
    ├── tests.py
    ├── urls.py
    └── views.py
```
I only got one static directory inside my app. My static looks like this:
```bash
├── static
│   ├── CACHE
│   │   ├── css
│   │   └── manifest.json
│   └── src
│       ├── input.css
│       ├── output.css
│       └── output.cssh
```

My staticfiles settings in the setting.py are as follows:
```python
STATIC_URL = "/static/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
```


> If you run collectstatic with verbose mode, do you see the Django-browser-reload files being collected?

They are in fact not being collected. I ran:
```bash 
python manage.py collectstatic --verbosity 2
```
and I got:
```bash
0 static files copied to '[...]/infrastructure-platform/staticfiles'.
```

I also tried:
```
python manage.py findstatic --verbosity 2 src/input.css
```
that's when it found that staticfile, though it looked only for files inside `serverdocumentation/static` and nowhere else, unlike in the example where it also looked inside the `django_browser_reload/static` directory.

I think it's really weird that 0 files are being collected when running collectstatic, shouldn't my input.css or output.css show up at least? I hope that answers all of your questions, if something is still unclear or if you need more information I will happily provide them, it's just that I am a complete beginner and it's my first time setting up a django project, so please bare with me if I sometimes can't answer your questions that well, I am trying my best. Thank you so much for trying to help me, I have wasted so many hours already on fixing this problem on my own...

**Comment by dipudangol2** [comment]
A workaround on this issue is you can take the files from static folder in django-browser-reload (if you're using a virtual env) and paste them into your static folder in the project which would then be accessible by the script and be run but it's a bit weird when it suddenly cannot find the file when it has been working correctly.

**Comment by adamchainz** [comment]
@juliu1902  Are you missing `AppDirectoriesFinder` in the `STATICFILES_FINDERS` setting? That is required to collect the files from the apps: https://docs.djangoproject.com/en/4.2/ref/settings/#staticfiles-finders

Consequently, it’s also required to make the Django admin work and various third-party packages that use static files, such as django-debug-toolbar.

**Comment by juliu1902** [comment]
> @juliu1902 Are you missing `AppDirectoriesFinder` in the `STATICFILES_FINDERS` setting? 

Oh my god, that was it. Thank you so much!!

**Comment by adamchainz** [comment]
Great!

I think we could prevent such errors recurring in the future by adding a system check that ensures:

1. `staticfiles` is installed
2. `AppDirectoriesFinder` is in `STATICFILES_FINDERS`
3. The middleware is installed

Django’s contrib apps do similar, for example `admin` checks for its dependencies:
https://github.com/django/django/blob/184d82d8488b1b31ade5b5a68b0040f1c267f2be/django/contrib/admin/checks.py#L56
