### ISSUE TITLE
want a docs pull-request for an 'autohotkey' Windows alternative?

### ISSUE THREAD

**Issue by andytwoods** [adamchainz/django-browser-reload#35]
### Description

Hi Adam,

I'm using the below with [AutoHotKey](https://www.autohotkey.com/) to quickly refresh my browser via a hotkey. It's Windows specific though (although I bet there's alternatives for Mac and Linux). 

I find it useful to refresh only at key moments, which this solution offers. 

Happy to add a section to your docs if you want, on this solution. Or if you'd prefer, I could just flesh this solution out in a blog, and just reference that. No probs if you feel this is not a good idea :)

Cheers,
Andy.

```
F2::
; Save current window
WinActivate,ahk_class Chrome_WidgetWin_1

; ---------------------------------------

; Refresh Chrome
Process, Exist, chrome.exe
    If(ErrorLevel) {
        WinActivate, ahk_pid %ErrorLevel%
        Send {F5}
    }

; ---------------------------------------
```

**Comment by adamchainz** [comment]
I think a blog post is the best place to describe your solution.

I'm happy to add a docs section with links to alternatives, for those who find django-browser-reload doesn't work for them, for whatever reason.

Have you tried django-browser-reload? How does it compare?

**Comment by andytwoods** [comment]
Hi Adam, 

here's a [draft](https://www.andytwoods.com/idebrowser-refresh-hotkey-productivity-tip/) of the blog-post. I've yet to add a Linux solution. 

I've yet to try django-browser-reload. But I will!

Cheers
Andy.

**Comment by adamchainz** [comment]
For the macOS solution, I think you should be able to use applescript to directly tell chrome to reload the open tab of the frontmost window, rather than switching back/forth. And probably similarly on Windows...

**Comment by adamchainz** [comment]
In fact, here is a solution: https://stackoverflow.com/a/23875893/1427135

**Comment by andytwoods** [comment]
Thanks!

**Comment by adamchainz** [comment]
Closing due to age, but feel free to open a PR in the future for an "alternatives" section.
