### ISSUE TITLE
Browser not reloading

### ISSUE THREAD

**Issue by datencoach** [adamchainz/django-browser-reload#68]
### Python Version

3.9.10

### Django Version

4.0.2

### Package Version

1.3.0

### Description

Did an update on django-tailwind from 2.x to 3.1.1 and also changed from browser-sync to django-browser-reload. Followed the update instructions and compared all steps to a previously updated project without any problems. 

But this time the browser just does not reload on changes. The script-Tag is in the source code of the page. Tailwind start does recognize the updated html or css. But the browser does not reload. No GET request to update the site is fired. 

Do you have any idea where I can look for the problem?

**Comment by datencoach** [comment]
Chrome and Firefox, sorry for leaving out.
There is no workers context in dev tools.

**Comment by adamchainz** [comment]
any logging in your console on main pages?

you can see what will be logged in the scripts

https://github.com/adamchainz/django-browser-reload/blob/main/src/django_browser_reload/static/django-browser-reload/reload-listener.js
https://github.com/adamchainz/django-browser-reload/blob/main/src/django_browser_reload/static/django-browser-reload/reload-worker.js

**Comment by shawnngtq** [comment]
Maybe relevant, `./manage runserver` works but `./manage runserver_plus` (django-extensions) doesn't

**Comment by adamchainz** [comment]
@shawnngtq that is probably a different issue. Can you open one? Also I don't particularly care to support django-extensions but if you can find a simple patch or docs fix I would merge that. Possibly `runserver_plus` doesn't support threads or long running views by default.

**Comment by shawnngtq** [comment]
It's ok, I just stick to the `./manage runserver`, this is a feature and not a bug. And not a very important one. 😁 

Just thought that datencoach might be doing it via `./manage runserver_plus`.

**Comment by datencoach** [comment]
No, I am using `runserver`. I did not have a chance to check during weekend and will not be able to check today. But there are no logging messages in the console. I will compare it with the working project and provide screenshots. Thanks for your help.

**Comment by datencoach** [comment]
No output to console in browser. Of course, no new request to the server. But CSS was rebuilt after change in HTML.


![2022-02-21 21_00_36](https://user-images.githubusercontent.com/51292314/155019768-34d4cedf-c274-46dc-a72f-958326997ab1.png)
![2022-02-21 21_01_52-home html - coworking - Visual Studio Code](https://user-images.githubusercontent.com/51292314/155019789-e2ac3aa0-f6c2-466d-94c0-c36374108910.png)

**Comment by adamchainz** [comment]
Please also check the worker logs as per the link in my first comment

**Comment by datencoach** [comment]
No workers in Javascript context and no workers in "shared workers"
![2022-02-22 07_11_27-Inspect with Chrome Developer Tools](https://user-images.githubusercontent.com/51292314/155073494-e208b5ea-c634-435d-bb05-6d799ae6df54.png)

As mentioned before the script tag is set in the source code
![2022-02-22 07_12_01-view-source_127 0 0 1_8000](https://user-images.githubusercontent.com/51292314/155073550-57f149fc-7b37-4a07-90fd-03e918f206c6.png)

**Comment by adamchainz** [comment]
You may have something on your page that prevents the script even starting.

If you see the listener script logs if it's not possible to start the worker:

https://github.com/adamchainz/django-browser-reload/blob/main/src/django_browser_reload/static/django-browser-reload/reload-listener.js

So either you should see that message, or the worker should start.

Are you allowing debug-level messages on your devtools console?

Are there other messages you're ignoring?

Can you try adding extra log messages to your local version of the script (edit it within your virtualenv) to see where it gets to?

**Comment by adamchainz** [comment]
Okay - that's interesting. Would you be able to add some `print()` statements into the view to determine if a connection is made, and if ping messages are sent?

https://github.com/adamchainz/django-browser-reload/blob/0d40e4edf65343513e04663a488ba2ac3a706e13/src/django_browser_reload/views.py#L145-L164

(I opened #69 to add some log messages to the source permanently, for future debugging.)

**Comment by datencoach** [comment]
Sure. 

View `events` is running on startup and page refresh. Function `event_stream` is called and while loop is running. `should_reload ` is set to `True `after change and save on a html template.

**Comment by adamchainz** [comment]
Huh. And this is with normal `runserver`, no packages replacing it, and you're not using the `--nothreading` option?

**Comment by adamchainz** [comment]
I would normally ask to reproduce the bug in a small project but I suspect it would be hard to do so without narrowing down the component.

**Comment by datencoach** [comment]
yes, straight `runserver`. nothing fancy. 
The only difference is Wagtail. The running project is straight Django.

No worries. I can work without reloading. And if no other user has the same problem, we should not spend too much time on it.

**Comment by adamchainz** [comment]
I'm happy to keep debugging, if you are.

As I understand, you added `print()`s within the `while` loop, so you could see messages were being `yield`ed by the view? That would imply that a worker is running and connected, and somehow receiving them...

**Comment by datencoach** [comment]
Sure, I am.

Yes, correct.
![2022-03-05 16_24_06-views py - coworking - Visual Studio Code](https://user-images.githubusercontent.com/51292314/156889690-ada76f81-f63b-4092-8292-259e938d663e.png)

![2022-03-05 16_24_22-views py - coworking - Visual Studio Code](https://user-images.githubusercontent.com/51292314/156889691-66aaf8a4-a262-4860-9601-fc70c9a35fce.png)

**Comment by adamchainz** [comment]
Okay, it seems impossible then that you'd not see a worker running. Clearly something is connected and receiving the events. Can you try checking the relevant debugging panels in both browsers, as per https://lihautan.com/Debugging%20web%20workers/  ?

**Comment by datencoach** [comment]
I still do not see any worker in `javascript context`
![2022-03-09 07_56_50-Coworking Space Stade](https://user-images.githubusercontent.com/51292314/157393976-b87ec873-86f6-44c7-8332-fa6735742f64.png)

But I can see it on ` chrome://inspect/#workers`
![2022-03-09 08_32_35-DevTools](https://user-images.githubusercontent.com/51292314/157394071-551c2c91-1325-4477-8afd-8885d0867666.png)

Still no reloading.

Checked on the "running" project. Same picture.
![2022-03-09 08_22_30-DevTools](https://user-images.githubusercontent.com/51292314/157394232-da9db0d5-415f-4563-967c-1e6f6ad46813.png)

**Comment by adamchainz** [comment]
Okay, I finally give up.

For your case, we've seen the server side component is running and sending messages, *and* the client side component is connecting and logging its "connected message". So it seems almost impossible that it wouldn't work.

Perhaps you have some kind of development tool (an option in devtools, or an extension) that is blocking the exact JS API's used to signal the reload.

I'd recommend you try a clean chrome profile with no extensions, or even another browser (Firefox!).

Happy to fix something if you get more data on this, but it seems the package is working fine for at least hundreds of people at this point, so it's probably not an issue here...

**Comment by datencoach** [comment]
Thanks for your help. Yes, I agree. The browser is not a problem as it is on any browser the same problem and it works with another project with identical setup. ... I could try screen recording to proof it is not working, but anyway. Fine with me. I will change my development setup shortly and it will be interesting to see if it works on the new laptop.
Thanks.

**Comment by rakyi** [comment]
I have what appears to be the same issue with both latest Firefox and Brave on macOS 12.5.

**Comment by adamchainz** [comment]
@rakyi Open a new issue if you have any new information. Please try capturing the debug logs at least.
