### ISSUE TITLE
Auto-refresh KO when updating view

### ISSUE THREAD

**Issue by ddahan** [adamchainz/django-browser-reload#82]
### Python Version

3.10.4

### Django Version

4.0

### Package Version

1.3.0

### (EDITED)

I carefully installed django-browser-reload and it has some unexpected behaviour with my project.
I decided to build your example project to find the issue, and the problem is the same within it.

Everything works as expected when I change and save a template file, I can see the changes occur in the browser.

But when I'm working with a view file, the server is actually reloaded when I save the file (which is something I expect):

```
/workspaces/dbr/example/core/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
May 05, 2022 - 09:21:44
Django version 3.2.13, using settings 'example.settings'
Starting development server at http://127.0.0.1:8001/
Quit the server with CONTROL-C.
```

However, django-browser-reload seems to do nothing at this time, hence I see no change in my browser.
Plus, once the server restarted, the hot-reloading does not work on templates too.
I need to refresh my browser manually in that case to see the changes made in python files, and make the hot-reloading work again.

Using your example project, changing a thing in a view such as `"title": "My Awesome Site"` and then saving, will do nothing.

Maybe a package upgrade broke something.

```
$ pip freeze

asgiref==3.4.1
Django==4.0.1
django-browser-reload==1.3.0
Jinja2==3.0.3
MarkupSafe==2.0.1
pywatchman==1.4.1
sqlparse==0.4.2
```

Thanks for your time.

**Comment by adamchainz** [comment]
Which browser?

django-browser-reload logs in the browser, at debug level. Can you check the log messages you see in your browser devtools?

**Comment by ddahan** [comment]
I'm using Latest Brave 1.38.111 (based onChromium: 101.0.4951.54 (arm64))
I tried Firefox too and the behaviour was exactly the same.

But I think I'm progressing on this issue. Maybe I should have specified first, but I'm using [dev containers](https://code.visualstudio.com/docs/remote/containers) to run the project. This could slightly change how the browser (in my host machine) and the server (on my docker container) communicate together.

In additional to the console logs you asked, I'll add the remote server logs, because they reveal connection errors.
The easiest way to share this IMO is to make a video of all the different workflows with all logs displayed:



https://user-images.githubusercontent.com/1933516/167250404-f273ba83-455a-4d4e-814c-ff5c0b7b073d.mov


Not seen on the video, sometimes before the SIGPIPE error there is:
```
[2022-05-07 09:46:47.839] [remoteagent] [error] Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)
```

### Troubleshooting ideas

- I have no knowledge at all in node.js, but I guess [this post](https://stackoverflow.com/questions/17245881/how-do-i-debug-error-econnreset-in-node-js) could be a good start to try to understand the `ECONNRESET` error.

- It seems that saving a template file kills the connection, but reopen it each time I save the template file again. That's why it seems to work with template file.

- In case you'd use VS Code and you'd be ok to dig a little bit further, I can provide the whole devcontainer source code to help.

I don't want to give up in this bug. My whole dev workflow is at stake ^^
Thanks for your time.

**Comment by ddahan** [comment]
**BUG SOLVED!!!!** 

It was because of me. Sorry about that. Some explanations:

When I use devcontainers, there are two different modes. The simplest mode has the source code on a local host, and is somehow synchronised to the remote host.

I guess having this file synchronisation enabled, while using a package like Django Browser Reload is very very error-prone.
