### ISSUE TITLE
Page requests stall when using asgi 

### ISSUE THREAD

**Issue by Jessica-Ryan** [adamchainz/django-browser-reload#93]
### Django Version

4.0.3

### Package Version

1.3.0

### Browser

Chrome

### Description

When using asgi for django channels page requests do not respond - result is pending and then fail after stall. Have had to uninstall this module due to this error.
Are you aware of the problem?

**Comment by adamchainz** [comment]
This is known and was reported in #87. The issue is likely to be a problem with Daphne or Channels not supporting `StreamingHttpResponse`.
